import pymysql

conn = pymysql.connect(host='localhost', user='root', password='root', database='school_crm', port=3306)
cursor = conn.cursor()

tables = [
    """CREATE TABLE IF NOT EXISTS asset_categories (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        name VARCHAR(100) NOT NULL,
        description TEXT,
        parent_id INT,
        depreciation_rate DECIMAL(5,2),
        useful_life_years INT,
        is_active BOOLEAN DEFAULT TRUE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (parent_id) REFERENCES asset_categories(id)
    )""",
    """CREATE TABLE IF NOT EXISTS assets (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        category_id INT,
        asset_code VARCHAR(50),
        name VARCHAR(255) NOT NULL,
        description TEXT,
        asset_type VARCHAR(50) DEFAULT 'fixed',
        brand VARCHAR(100),
        model VARCHAR(100),
        serial_number VARCHAR(100),
        purchase_date DATE,
        purchase_price DECIMAL(12,2),
        vendor_id INT,
        warranty_expiry DATE,
        warranty_details TEXT,
        location VARCHAR(200),
        room_number VARCHAR(50),
        assigned_to VARCHAR(100),
        `condition` VARCHAR(30) DEFAULT 'good',
        status VARCHAR(30) DEFAULT 'active',
        current_value DECIMAL(12,2),
        depreciation_method VARCHAR(30) DEFAULT 'straight_line',
        salvage_value DECIMAL(12,2),
        useful_life_years INT,
        last_audit_date DATE,
        photo_url VARCHAR(255),
        qr_code_url VARCHAR(255),
        notes TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (category_id) REFERENCES asset_categories(id)
    )""",
    """CREATE TABLE IF NOT EXISTS asset_maintenance (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        asset_id INT NOT NULL,
        maintenance_type VARCHAR(50) DEFAULT 'repair',
        description TEXT NOT NULL,
        reported_date DATE NOT NULL,
        scheduled_date DATE,
        completed_date DATE,
        vendor_name VARCHAR(200),
        cost DECIMAL(12,2),
        status VARCHAR(30) DEFAULT 'pending',
        priority VARCHAR(20) DEFAULT 'medium',
        technician VARCHAR(100),
        notes TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE
    )""",
    """CREATE TABLE IF NOT EXISTS inventory_categories (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        name VARCHAR(100) NOT NULL,
        description TEXT,
        is_active BOOLEAN DEFAULT TRUE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
    )""",
    """CREATE TABLE IF NOT EXISTS inventory_items (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        category_id INT,
        name VARCHAR(255) NOT NULL,
        description TEXT,
        sku VARCHAR(50),
        quantity INT DEFAULT 0,
        unit VARCHAR(50),
        unit_price DECIMAL(12,2),
        min_stock_level INT DEFAULT 0,
        max_stock_level INT,
        reorder_quantity INT,
        location VARCHAR(100),
        expiry_date DATE,
        is_lab_item BOOLEAN DEFAULT FALSE,
        is_active BOOLEAN DEFAULT TRUE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (category_id) REFERENCES inventory_categories(id) ON DELETE CASCADE
    )""",
    """CREATE TABLE IF NOT EXISTS inventory_transactions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        item_id INT NOT NULL,
        transaction_type VARCHAR(20) NOT NULL,
        quantity INT NOT NULL,
        reference_type VARCHAR(50),
        reference_id INT,
        issued_to VARCHAR(200),
        remarks VARCHAR(255),
        created_by INT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
        FOREIGN KEY (created_by) REFERENCES users(id)
    )""",
    """CREATE TABLE IF NOT EXISTS purchase_requests (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        request_number VARCHAR(50),
        title VARCHAR(255) NOT NULL,
        description TEXT,
        request_type VARCHAR(30) DEFAULT 'manual',
        priority VARCHAR(20) DEFAULT 'medium',
        requested_by INT,
        department VARCHAR(100),
        items_json TEXT,
        estimated_total DECIMAL(12,2),
        approved_by INT,
        approved_at DATETIME,
        status VARCHAR(30) DEFAULT 'pending',
        rejection_reason TEXT,
        notes TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (requested_by) REFERENCES users(id),
        FOREIGN KEY (approved_by) REFERENCES users(id)
    )""",
    """CREATE TABLE IF NOT EXISTS purchase_orders_inv (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        po_number VARCHAR(50),
        purchase_request_id INT,
        vendor_name VARCHAR(200) NOT NULL,
        vendor_contact VARCHAR(100),
        vendor_email VARCHAR(120),
        vendor_address TEXT,
        order_date DATE NOT NULL,
        expected_delivery DATE,
        actual_delivery DATE,
        items_json TEXT,
        subtotal DECIMAL(12,2),
        tax_amount DECIMAL(12,2),
        discount_amount DECIMAL(12,2),
        total_amount DECIMAL(12,2),
        payment_terms VARCHAR(200),
        delivery_terms VARCHAR(200),
        quality_check BOOLEAN DEFAULT FALSE,
        quality_notes TEXT,
        status VARCHAR(30) DEFAULT 'draft',
        notes TEXT,
        created_by INT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id),
        FOREIGN KEY (created_by) REFERENCES users(id)
    )""",
    """CREATE TABLE IF NOT EXISTS vendor_quotations (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        purchase_request_id INT,
        vendor_name VARCHAR(200) NOT NULL,
        vendor_contact VARCHAR(100),
        vendor_email VARCHAR(120),
        quotation_number VARCHAR(50),
        quotation_date DATE,
        valid_until DATE,
        items_json TEXT,
        total_amount DECIMAL(12,2),
        delivery_days INT,
        payment_terms VARCHAR(200),
        warranty_terms VARCHAR(200),
        rating INT,
        is_selected BOOLEAN DEFAULT FALSE,
        notes TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (purchase_request_id) REFERENCES purchase_requests(id)
    )""",
    """CREATE TABLE IF NOT EXISTS asset_disposals (
        id INT AUTO_INCREMENT PRIMARY KEY,
        school_id INT NOT NULL,
        asset_id INT NOT NULL,
        disposal_type VARCHAR(30) NOT NULL,
        disposal_date DATE NOT NULL,
        reason TEXT NOT NULL,
        book_value DECIMAL(12,2),
        disposal_value DECIMAL(12,2),
        buyer_name VARCHAR(200),
        buyer_contact VARCHAR(100),
        approved_by INT,
        certificate_url VARCHAR(255),
        status VARCHAR(30) DEFAULT 'pending',
        notes TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
        FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
        FOREIGN KEY (approved_by) REFERENCES users(id)
    )"""
]

for sql in tables:
    tname = sql.split('IF NOT EXISTS ')[1].split(' ')[0]
    try:
        cursor.execute(sql)
        print(f"OK {tname}")
    except Exception as e:
        print(f"ERR {tname}: {e}")

conn.commit()
cursor.close()
conn.close()
print("\nDone! All inventory tables created.")
