"""add leave_date

Revision ID: 0807cff5f0b7
Revises: d7d020dc8bf1
Create Date: 2026-07-10 11:47:36.930195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0807cff5f0b7'
down_revision = 'd7d020dc8bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('leave_date')

    # ### end Alembic commands ###
