"""add tuition_fee_yearly

Revision ID: 19f00bbce0bc
Revises: 43c3b65b89e4
Create Date: 2026-07-09 16:04:40.885329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f00bbce0bc'
down_revision = '43c3b65b89e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tuition_fee_yearly', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tuition_fee_paid', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_column('tuition_fee_paid')
        batch_op.drop_column('tuition_fee_yearly')

    # ### end Alembic commands ###
