"""add_assigned_class_id_to_exam_halls

Revision ID: 44d537fd8c6b
Revises: 06e6972e3f9e
Create Date: 2026-07-13 16:17:24.697851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d537fd8c6b'
down_revision = '06e6972e3f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_halls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'classes', ['assigned_class_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_halls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_class_id')

    # ### end Alembic commands ###
