"""add paper_status to exam_schedules

Revision ID: 99a916183cfd
Revises: 9ffa31d0af04
Create Date: 2026-07-17 15:42:57.993108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a916183cfd'
down_revision = '9ffa31d0af04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_status', sa.Enum('scheduled', 'cancelled', 'postponed'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedules', schema=None) as batch_op:
        batch_op.drop_column('paper_status')

    # ### end Alembic commands ###
