"""add late_days to fee_payments

Revision ID: 9ffa31d0af04
Revises: f4aa8ca07e20
Create Date: 2026-07-16 17:18:32.504279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffa31d0af04'
down_revision = 'f4aa8ca07e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_column('late_days')

    # ### end Alembic commands ###
