"""add admission_number enrollment_no unique constraints

Revision ID: b8c6fab3171a
Revises: 19f00bbce0bc
Create Date: 2026-07-10 10:56:17.438000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c6fab3171a'
down_revision = '19f00bbce0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enrollment_no', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_school_admission_number', ['school_id', 'admission_number'])
        batch_op.create_unique_constraint('uq_school_enrollment_no', ['school_id', 'enrollment_no'])
        batch_op.create_unique_constraint('uq_class_section_roll_no', ['school_id', 'current_class_id', 'current_section_id', 'roll_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('uq_class_section_roll_no', type_='unique')
        batch_op.drop_constraint('uq_school_enrollment_no', type_='unique')
        batch_op.drop_constraint('uq_school_admission_number', type_='unique')
        batch_op.drop_column('enrollment_no')
        batch_op.drop_column('admission_number')

    # ### end Alembic commands ###
