"""add linked_student_id

Revision ID: d7d020dc8bf1
Revises: b8c6fab3171a
Create Date: 2026-07-10 11:36:52.534134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d020dc8bf1'
down_revision = 'b8c6fab3171a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_student_id', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('uq_school_roll_no'))
        batch_op.create_unique_constraint('uq_class_section_roll_no', ['school_id', 'current_class_id', 'current_section_id', 'roll_no'])
        batch_op.create_foreign_key(None, 'students', ['linked_student_id'], ['admission_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_class_section_roll_no', type_='unique')
        batch_op.create_index(batch_op.f('uq_school_roll_no'), ['school_id', 'roll_no'], unique=True)
        batch_op.drop_column('linked_student_id')

    # ### end Alembic commands ###
