"""add postponed_to to exam_schedules

Revision ID: f4aa8ca07e20
Revises: 44d537fd8c6b
Create Date: 2026-07-16 14:24:19.892116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4aa8ca07e20'
down_revision = '44d537fd8c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postponed_to', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_schedules', schema=None) as batch_op:
        batch_op.drop_column('postponed_to')

    # ### end Alembic commands ###
